### ISSUE TITLE
Why comments the code in line 333 and 334 ?

### ISSUE THREAD

**Issue by Innericy** [dsforza96/yocto-hair#1]
https://github.com/dsforza96/yocto-hair/blob/f4ffe77506e1a0700caa4a0a932890e62ea671e7/libs/yocto_extension/yocto_extension.cpp#L333

It looks different from the PBRT's code.
Why ? 
Will it makes noise ?

**Comment by antoniomuso** [comment]
The commented operation is done out of the function.
